set_property PACKAGE_PIN U17 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property PACKAGE_PIN T17 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property PACKAGE_PIN T18 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property PACKAGE_PIN W19 [get_ports d]
set_property IOSTANDARD LVCMOS33 [get_ports d]

set_property PACKAGE_PIN R2 [get_ports add]
set_property IOSTANDARD LVCMOS33 [get_ports add]
set_property PACKAGE_PIN T1 [get_ports sub]
set_property IOSTANDARD LVCMOS33 [get_ports sub]
set_property PACKAGE_PIN U1 [get_ports mul]
set_property IOSTANDARD LVCMOS33 [get_ports mul]
set_property PACKAGE_PIN W2 [get_ports div]
set_property IOSTANDARD LVCMOS33 [get_ports div]

set_property PACKAGE_PIN U18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]



set_property PACKAGE_PIN W5 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports clock]


set_property PACKAGE_PIN W7 [get_ports {out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[7]}]
set_property PACKAGE_PIN W6 [get_ports {out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[6]}]
set_property PACKAGE_PIN U8 [get_ports {out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[5]}]
set_property PACKAGE_PIN V8 [get_ports {out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[4]}]
set_property PACKAGE_PIN U5 [get_ports {out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[3]}]
set_property PACKAGE_PIN V5 [get_ports {out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
set_property PACKAGE_PIN U7 [get_ports {out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
set_property PACKAGE_PIN V7 [get_ports {out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]

set_property PACKAGE_PIN U2 [get_ports {enable[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable[0]}]
set_property PACKAGE_PIN U4 [get_ports {enable[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable[1]}]
set_property PACKAGE_PIN V4 [get_ports {enable[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable[2]}]
set_property PACKAGE_PIN W4 [get_ports {enable[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable[3]}]